name: Check Python code format

on:
  pull_request:
    paths:
      - "requirements.txt"
      - "**.py"
      - ".github/workflows/check-python-code-format.yml"
  push:
    paths:
      - "requirements.txt"
      - "**.py"
      - ".github/workflows/check-python-code-format.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-python-code-format:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python3 -m pip install pip-tools
          pip-sync

      - name: Format with Black
        run: black --check carriersettings_extractor.py

      - name: Lint with Ruff
        run: ruff check carriersettings_extractor.py
